### ISSUE TITLE
Direct recursion is disallowed when it's not guaranteed anyway

### ISSUE THREAD

**Issue by jkeegan314** [CubieDev/TwitchMarkovChain#1]
Comments with "x x x" should be entered in the database if at least k% of messages of the format "x x y" (where y can equal x) are of the format "x x y" where y ≠ x

This will allow for the bot to produce messages like "LUL LUL LUL BANNED" if "LUL LUL BANNED" and "LUL LUL LUL" are both in the database. Of course, the message could be 20 LULs, but the probability of this is ((100-k)/100)^20 which is gonna be pretty low if k is something like 50

**Comment by CubieDev** [comment]
Will look into implementing this.

**Comment by CubieDev** [comment]
This has now been implemented into the most recent version.
