### ISSUE TITLE
Incompatible databases

### ISSUE THREAD

**Issue by RobotoDent** [CubieDev/TwitchMarkovChain#4]
Is it possible to make databases from older versions of the bot work with the newest one? It breaks whenever I give it my database that's got the most chat messages gathered.

**Comment by CubieDev** [comment]
Yes, this is possible.
My apologies for the late reply. I really figured I would have gotten a notification or email about an issue popping up.

I created a `converters` branch specifically for scripts that convert databases between versions. You can access them here: https://github.com/CubieDev/TwitchMarkovChain/tree/converters

I will look into my Github settings to hopefully enable notifications when these messages come in.
