### ISSUE TITLE
Not enough learned information

### ISSUE THREAD

**Issue by Bruggles718** [CubieDev/TwitchMarkovChain#7]
I don't seem to understand how much information is needed for the bot to work. It seems that no matter how many messages I send, !generate just gives me "There is not enough learned information yet." I really have no clue what I'm doing wrong, if anybody could help me.

**Comment by CubieDev** [comment]
Hello!

The bot takes a bit of time to learn enough to always generate. To give a bit of insight, if you don't supply it with any text like `!generate I am`, then it will pick a random character out of the alphabet, and see if it knows a word that starts with that character. However, if it picks a character such as q, z, or v, it might not have already learned a word that starts with that character. In that case, it wiill say "There is not enough learned information yet.".

Well, you might ask, "How do I teach it properly?". The bot learns in sequences of 3 words. That means that a bot would learn the following phrases from the previous sentence: `The bot learns`, `bot learns in`, `learns in sequences`, `in sequences of`, `sequences of 3`, `of 3 words.`.
Furthermore it only learns these once it has stored up enough of these sequences. I see now that it needs 500 of these before it batch-learns them all, which I realise is too much for smaller chats. As such, I have heavily reduced this in favour of smaller chats, down to 25. I would advise downloading the newest version.
After that, it should quickly start to learn these phrases, and you will start getting results! 

Let me know if you have any more issues!

- Tom

**Comment by Bruggles718** [comment]
Thank you so much, I really appreciate it!
